//
// Created by george on 2018/11/6.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#ifndef MYLAME_COM_GEORGE_MYLAME_UTIL_LAMEUTIL_H
#define MYLAME_COM_GEORGE_MYLAME_UTIL_LAMEUTIL_H
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_george_mylame_util_LameUtil
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_george_mylame_util_LameUtil_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_george_mylame_util_LameUtil
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_george_mylame_util_LameUtil_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_george_mylame_util_LameUtil
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_george_mylame_util_LameUtil_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_george_mylame_util_LameUtil
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_george_mylame_util_LameUtil_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

